### ISSUE TITLE
Globstar in a subfolder - not matching

### ISSUE THREAD

**Issue by fidian** [micromatch/micromatch#102] opened 2017-08-23 17:54 UTC
Here's a pretty illustrative example:

```
> mm.isMatch("file.txt", "**/!(folder).txt")
true
> mm.isMatch("a/dir/file.txt", "*/dir/**/!(folder).txt")
false
```

The second one should be `true`, shouldn't it? I'm using version 3.0.4.

**Comment by jonschlinkert** [comment] 2017-08-24 03:00
> The second one should be true, shouldn't it?

I agree, it seems like that should match, but I need to reference bash docs and see how that's handled with one and two stars.

marking as a duplicate of https://github.com/micromatch/micromatch/issues/100

**Closed by jonschlinkert** 2017-08-24 03:00 UTC
