### ISSUE TITLE
Incorrect behaviour for for patterns with underscore

### ISSUE THREAD

**Issue by eGavr** [micromatch/micromatch#135] opened 2018-07-16 23:14 UTC
Hi!

I've met a bug using the latest version of micromatch (3.1.10).

## Please describe the **minimum necessary steps** to reproduce this issue:

```js
require('anymatch')(['dir-{suffix1,suffix2}/**/_*.js'], 'dir-suffix1/f_.js');
```

## What is happening (but shouldn't):

The result is `true`.

## What should be happening instead?

I expect the result to be `false`.

Thanks

**Comment by jonschlinkert** [comment] 2018-07-18 14:42
@eGavr ping

**Comment by jonschlinkert** [comment] 2018-07-19 01:07
Closing since I cannot reproduce this in micromatch. 

```js
const mm = require('micromatch');
console.log(mm.any('dir-suffix1/f_.js', ['dir-{suffix1,suffix2}/**/_*.js'])); // false
```

Ping @es128, looks like this might be a bug in anymatch in case you want to look into it.

**Closed by jonschlinkert** 2018-07-19 01:07 UTC
