### ISSUE TITLE
makeRe does not handle parens as part of filename - different from minimatch

### ISSUE THREAD

**Issue by mrcoles** [micromatch/micromatch#123] opened 2018-04-07 23:30 UTC
## Please describe the **minimum necessary steps** to reproduce this issue:

In a new directory using bash:

```bash
yarn init -qy && yarn add micromatch@3.1.9 minimatch@3.0.4
```

Then in the `node` repl:

```javascript
const minimatch = require('minimatch');
const micromatch = require('micromatch');

const p = "/tmp/parens (1)/*.js";
const f = "/tmp/parens (1)/a.js";

const miniRe = minimatch.makeRe(p);
f.match(miniRe);
// > [ '/tmp/parens (1)/a.js', index: 0, input: '/tmp/parens (1)/a.js' ]

const microRe = micromatch.makeRe(p);
f.match(microRe);
// > null
```

## What is happening (but shouldn't):

The regular expression that is generated by micromatch does not match `f`.

## What should be happening instead?

I believe it should match and work the same as minimatch?

I encountered this while seeing tests fall for `parcel` where it does some glob matching and the parent directory of where I was running it had parentheses in its path: https://github.com/parcel-bundler/parcel/blob/434b86c92b19e2c7de13a121600d0533c1138169/src/assets/GlobAsset.js#L21

**Comment by jonschlinkert** [comment] 2018-04-08 01:44
Looks like a bug. That should work. I know where that's handled, I'll get a fix pushed up.

**Comment by jonschlinkert** [comment] 2018-04-08 14:31
closing since this isn't a bug, and I confirmed that the solution works. If you still have trouble with it, please feel free to re-open the issue or continue the conversation here.

**Closed by jonschlinkert** 2018-04-08 14:31 UTC
