### ISSUE TITLE
micromatch 3.1.10 package at registry.npmjs.org has bad file time stamps

### ISSUE THREAD

**Issue by Robert-J-Slover** [micromatch/micromatch#138] opened 2018-09-19 22:29 UTC
## Please describe the **minimum necessary steps** to reproduce this issue:

The release tarball retrieved for Micromatch 3.1.10 from the NPM javascript registry at [https://registry.npmjs.org/micromatch/-/micromatch-3.1.10.tgz](https://registry.npmjs.org/micromatch/-/micromatch-3.1.10.tgz) contains files whose time stamps are all midnight of January 1, 1970 (in GMT). The previous release [https://registry.npmjs.org/micromatch/-/micromatch-3.1.9.tgz](https://registry.npmjs.org/micromatch/-/micromatch-3.1.9.tgz) contains perfectly reasonable time stamps. This can be demonstrated by simply listing the tarball contents, e.g.:

```
-sh-4.2$ curl -s https://registry.npmjs.org/micromatch/-/micromatch-3.1.10.tgz | gunzip -c | TZ=GMT tar -tvf -                                                                     
-rw-r--r-- 0/0            3202 1970-01-01 00:00 package/package.json
-rw-r--r-- 0/0            1129 1970-01-01 00:00 package/CHANGELOG.md
-rw-r--r-- 0/0           23853 1970-01-01 00:00 package/index.js
-rwxr-xr-x 0/0            1088 1970-01-01 00:00 package/LICENSE
-rw-r--r-- 0/0           38227 1970-01-01 00:00 package/README.md
-rw-r--r-- 0/0            6148 1970-01-01 00:00 package/lib/.DS_Store
-rw-r--r-- 0/0              52 1970-01-01 00:00 package/lib/cache.js
-rw-r--r-- 0/0            1827 1970-01-01 00:00 package/lib/compilers.js
-rw-r--r-- 0/0            2027 1970-01-01 00:00 package/lib/parsers.js
-rw-r--r-- 0/0            7258 1970-01-01 00:00 package/lib/utils.js
```
vs.
```
-sh-4.2$ curl -s https://registry.npmjs.org/micromatch/-/micromatch-3.1.9.tgz | gunzip -c | TZ=GMT tar -tvf -                                                                      
-rw-r--r-- 0/0            3201 2018-02-24 07:55 package/package.json
-rw-r--r-- 0/0            1129 2017-07-03 21:32 package/CHANGELOG.md
-rw-r--r-- 0/0           23853 2018-02-24 07:54 package/index.js
-rwxr-xr-x 0/0            1088 2018-02-18 18:22 package/LICENSE
-rw-r--r-- 0/0           38227 2017-09-11 05:36 package/README.md
-rw-r--r-- 0/0            6148 2016-09-05 15:25 package/lib/.DS_Store
-rw-r--r-- 0/0              52 2017-05-29 06:10 package/lib/cache.js
-rw-r--r-- 0/0            1827 2018-02-18 18:44 package/lib/compilers.js
-rw-r--r-- 0/0            2027 2018-02-18 14:27 package/lib/parsers.js
-rw-r--r-- 0/0            7258 2018-02-24 07:51 package/lib/utils.js
```

## What is happening (but shouldn't):

I only noticed this because it broke the continuous deployment installation for a project belonging to another group at our company. I was asked to help diagnose. The project indirectly uses the 'readdirp' NodeJS module, which six days ago switched from using 'minimatch' to using 'micromatch'. The particular project verifies files after they are installed using a combination of file sizes, check sums, time stamps, and permissions. The installer flags any installed files with a time stamp of January 1, 1970 as an error, since this usually means that the installer was unable to restore the proper file time stamp. We can work around the problem, but there is obviously something wrong here.

## What should be happening instead?

I believe the file time stamps should match those from the release tarball available directly from the micromatch GitHub: [https://github.com/micromatch/micromatch/archive/3.1.10.tar.gz](https://github.com/micromatch/micromatch/archive/3.1.10.tar.gz).

**Comment by jonschlinkert** [comment] 2018-11-05 12:16
@Robert-J-Slover I can't reproduce this, it seems like something on your end or maybe it was a temporary issue with NPM? Please try deleting `node_modules` first, then reinstall everything. 

Closing for now, but please reopen if the problem persists, we could publish a patch to see if it fixes the issue.

**Closed by jonschlinkert** 2018-11-05 12:16 UTC

**Comment by yongelee** [comment] 2018-12-29 16:33
same problem. I can't deploy to AWS elastic beanstalk because of this problem.

**Comment by yongelee** [comment] 2018-12-29 17:39
i had to manually edit every file's timestamp that was outdated in this package folder.
