### ISSUE TITLE
negation extglob not matching correctly with wildcard

### ISSUE THREAD

**Issue by fidian** [micromatch/micromatch#103] opened 2017-08-23 20:03 UTC
```
> mm.isMatch("a/b/c.txt", "*/b/!(c).txt")
false
> mm.isMatch("a/b/cc.txt", "*/b/!(c).txt")
false
```

Why is the second one not matching?

**Comment by jonschlinkert** [comment] 2017-08-24 02:57
going to mark this as a duplicate of https://github.com/micromatch/micromatch/issues/100

**Closed by jonschlinkert** 2017-08-24 02:57 UTC

**Comment by jonschlinkert** [comment] 2017-09-08 02:25
Sorry for the delay. These should be working now.  

related 

https://github.com/micromatch/nanomatch/commit/acde39356bc0708b2e26149e6c084ae505fb9021
