### ISSUE TITLE
micromatch throws in certain cases

### ISSUE THREAD

**Issue by danez** [micromatch/micromatch#99] opened 2017-07-22 13:25 UTC
## Please describe the **minimum necessary steps** to reproduce this issue:

see https://github.com/babel/babel/pull/5992

## What is happening (but shouldn't):

```
TypeError: utils.pascal is not a function
    at Snapdragon.Base.is (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/base/index.js:105:30)
    at Snapdragon.Base (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/base/index.js:43:10)
    at new Snapdragon (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/snapdragon/index.js:23:8)
    at Object.utils.instantiate (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/lib/utils.js:43:18)
    at parse (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:702:28)
    at memoize (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:830:13)
    at Function.micromatch.parse (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:716:10)
    at create (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:652:44)
    at /Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:661:16
    at memoize (/Users/danieltschinder/Documents/Github/babel/packages/babel-core/node_modules/micromatch/index.js:830:13)
```

## What should be happening instead?

no error

I am not able to reproduce this in a simple case. I tried using codesandbox and receive a similar error. https://codesandbox.io/s/0grnwozBK

So my guess is that the lazy loading [here](https://github.com/node-base/base/blob/0.11.1/utils.js#L3) is somehow interfeering with certain other tools that hook into require (like testing tools and or in the case of codesandbox propbably some other tool that hijacks require to make it work in the browser).

Sorry that I do not have more details here.

**Comment by jonschlinkert** [comment] 2017-07-22 13:32
> Sorry that I do not have more details here.

No worries, I appreciate you creating the issue. I'll dive into this and see what's happening. Agreed that it looks like a bug. Also, we tried to remove all lazy-loading modules. If there is still one in the dep tree, I'll get that fixed.

**Comment by danez** [comment] 2017-07-22 13:35
Maybe an update of snapdragon from 0.8 to 0.11 would already solve this problem. I tried to do it but then noticed that I would also have to update nanomatch and never got it working.

**Comment by jonschlinkert** [comment] 2017-07-22 14:48
Good point, I think that might resolve it. There were other API changes in snapdragon that would cause the tests to fail in all of the libs using it. I'm already looking into it, I'll update here as soon as it's resolved. thx

**Comment by jonschlinkert** [comment] 2017-07-22 19:07
quick update. I should be able to push something up later today to fix this. I'm sorry this caused problems for you, I know how frustrating it can be when something breaks your flow.

**Comment by danez** [comment] 2017-07-22 20:04
No hurry, I just noticed it when I tried updating micromatch from 2.x to 3.x.

**Comment by jonschlinkert** [comment] 2017-07-22 23:17
great I think I'm just about finished with this, but I won't have time to push it up today. You were right about the cause. For now, I'm just going to patch bump snapdragon to 0.8.x to fix the bug. fwiw the latest version of snapdragon has API changes that wouldn't really provide any benefits to micromatch atm, but the next release of Snapdragon will, so I'll upgrade Snapdragon then.  

If this is preventing you from getting something done, please let me know and I'll do what I can to get it pushed up faster

**Comment by jonschlinkert** [comment] 2017-09-08 01:42
Really sorry for the delay. I believe this is fixed now so I'm going to go ahead and close, but please reopen or create another issue if this happens again.

**Closed by jonschlinkert** 2017-09-08 01:42 UTC
Labels: bug

**Comment by benpolinsky** [comment] 2017-10-30 12:57
Hi,

I'm receiving a similar error, only when running integration tests. I've had a tough time reproducing the error in a more isolated case.

When I get a chance I can try to narrow down my use case and replicate, but this has been nagging me for a few weeks.

Sometimes the error is 
`TypeError: utils.isObject is not a function`

and other times the error is 
`TypeError: utils.define is not a function`

Backtrace:
<details>
  at base (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\use\index.js:13:14)
        at Compiler (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\snapdragon\lib\compiler.js:28:3)
        at new Snapdragon (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\snapdragon\index.js:25:19)
        at Object.<anonymous>.utils.instantiate (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\lib\utils.js:43:18)
        at parse (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:738:28)
        at memoize (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:866:13)
        at Function.Object.<anonymous>.micromatch.parse (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:752:
10)
        at create (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:688:44)
        at C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:697:16
        at memoize (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:866:13)
        at Function.Object.<anonymous>.micromatch.create (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:686
:10)
        at makeRe (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:581:29)
        at memoize (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:866:13)
        at Function.Object.<anonymous>.micromatch.makeRe (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:598
:10)
        at matcher (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:485:23)
        at memoize (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:866:13)
        at Function.Object.<anonymous>.micromatch.isMatch (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:16
8:17)
        at Function.Object.<anonymous>.micromatch.any (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\node_modules\micromatch\index.js:274:20
)
        at isAllowed (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\tsJsonToMarkdown.js:32:16)
        at Ware.<anonymous> (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\@bentley\bemetalsmith-typedoc-json-to-markdown\tsJsonToMarkdown.js:13:17)
        at Ware.<anonymous> (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\wrap-fn\index.js:45:19)
        at next (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\ware\lib\index.js:85:20)
        at Ware.Object.<anonymous>.Ware.run (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\ware\lib\index.js:88:3)
        at Metalsmith.<anonymous> (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\thunkify\index.js:43:12)
        at next (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\unyield\node_modules\co\index.js:90:21)
        at Metalsmith.<anonymous> (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\unyield\node_modules\co\index.js:45:5)
        at Metalsmith.next (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\unyield\node_modules\co\index.js:90:21)
        at Metalsmith.<anonymous> (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\unyield\node_modules\co\index.js:93:18)
        at Immediate._onImmediate (C:\Users\Ben.Polinsky\Source\Repos\docs-gen\packages\bemetalsmith\node_modules\unyield\node_modules\co\index.js:52:14)
        at runCallback (timers.js:781:20)
        at tryOnImmediate (timers.js:743:5)
        at processImmediate [as _immediateCallback] (timers.js:714:5)

</details>

Any help or direction is much appreciated.
Thank you.

**Comment by jonschlinkert** [comment] 2017-10-30 15:56
Hi @benpolinsky, is that the entire stack trace? We'll need more info to help debug. For starters:

- what OS are you using?
- what code were you running that created the error?
- is there a repository we can look at?
- anything else you can think of that might help with debugging
