### ISSUE TITLE
Will micromatch gradually phase out CJS support instead of abruptly (cf multimatch)?

### ISSUE THREAD

**Issue by webketje** [micromatch/micromatch#231] opened 2022-02-06 22:26 UTC
Hi there, as the maintainer of [Metalsmith](https://github.com/metalsmith/metalsmith) I had to witness in horror that an NPM dependency most of our core plugins use (multimatch) has dropped support for CJS modules altogether in an effort to "get the community behind a single standard". While I respect the cause, and do plan to add ESM support, this is way too quick and leaves me scrambling to update all plugins, plus I would like to keep providing CJS support.

The core method `Metalsmith.match` uses micromatch under the hood. I just want to make sure that micromatch will not suddenly drop CJS support, but if it does get there, could it choose a gradual, dual packaging strategy instead? 

(PS + same question for gray-matter, also used by `Metalsmith.frontmatter`)

**Comment by jonschlinkert** [comment] 2022-02-06 22:37
We have no plans to phase out of CJS anytime soon. I know exactly what you mean, and I've actively avoided using libraries that do this.

I also respect the cause, as there are also many advantages to ESM, tree shaking, etc. But IMHO this transition should have, and could have been less pain for the community. For me personally, ESM has been a nightmare to use, and a nightmare to maintain. It was designed to intentionally break compatibility with CJS, which is not entirely because of technical constraints, which I won't get into here. 

Thanks for asking.

**Comment by jonschlinkert** [comment] 2022-03-24 18:49
closing since I believe this was resolved.

**Closed by jonschlinkert** 2022-03-24 18:49 UTC
